- hosts: localhost
  connection: local
  become: true

 pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages_deb.yml
    - include: tasks/settings.yml
    - include: tasks/ssh.yml
