- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    special_time: daily
    job: "/usr/bin/ansible-pull -o --vault-password-file /root/.ansible-vault-password -U https://github.com/mnul/ansible-pull.git > /dev/null"
