- name: Install packages
  apt:
    name:
      - tmux
      - htop
      - sudo
      - xclip

- name: Install Debian packages
  apt:
    name:
      - netselect
  when: ansible_distribution == "Debian"
