- name: Update all packages
  apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS", "Raspbian", "Armbian"]


- name: Install packages
  apt:
    name:
      - cron
      - tmux
      - htop
      - sudo
      - xclip
      - curl
      - cifs-utils
      - nfs-common
      - net-tools
      - neofetch
      - tree
      - gnupg2
      - ncdu
      - dnsutils
      - python3
      - python3-pip
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS", "Raspbian", "Armbian"]

- name: Install Debian packages
  apt:
    name:
      - netselect
    state: present
  when: ansible_distribution == "Debian"
