- name: Install packages
  apt:
    name:
      - cron
      - tmux
      - htop
      - sudo
      - xclip
      - curl
      - cifs-utils
      - nfs-common
      - net-tools
      - neofetch
      - tree
      - gnupg2
      - ncdu
      - dnsutils
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS", "Raspbian"]

- name: Install Debian packages
  apt:
    name:
      - netselect
    state: present
  when: ansible_distribution == "Debian"

- name: Install ansible ppa
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

- name: Install ansible
  apt:
    name:
      - ansible
    state: latest
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS", "Raspbian"]